Repository BHoM/GSA_Toolkit, pull requests merged in 2020-08, with the labels that each got.

#188 Remove support for pulling results with filter request, adding error messaging
  GSA_Adapter/CRUD/Read.cs
  GSA_Adapter/CRUD/ReadResults.cs
Labels: type:compliance

#189 Renamed RigidLink master/slave to primary/secondary
  GSA_Adapter/CRUD/Create.cs
  GSA_Adapter/Convert/FromGsa/Elements/RigidLink.cs
  GSA_Adapter/Convert/ToGsa/Elements/RigidLink.cs
Labels: type:compliance, type:external-api-changes

#190 Align with changes of Load<T> to IELementLoad<T>
  GSA_Adapter/Convert/ToGsa/Group.cs
  GSA_Adapter/Convert/ToGsa/Loads/AreaLoads.cs
  GSA_Adapter/Convert/ToGsa/Loads/BarLoads.cs
  GSA_Adapter/Convert/ToGsa/Loads/NodeLoad.cs
  GSA_Adapter/GSAAdapter.cs
Labels: type:external-api-changes
